### ISSUE TITLE
World Map - Fix the Seams

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#106]
At many zoom levels, there are ugly seams in the map.

This is to ideally fix that while retaining zoom.

The idea of only having a few fixes zooms (100%, 200%, 50%, etc.) to fix the problem has also been suggested, and may be either an interim or permanent solution.

**Comment by JimOfLeisure** [comment]
I'm reasonably sure the seams are due to OpenGL interpolating the opaque/transparent edges of the individual tiles when placing them. I can think of a few possible remedies:

- Use a shader to set filter GL_NEAREST to prevent interpolation
- Create a whole map texture rather than use place individual tiles; the prebuilt texture will have no transparency to interpolate
- Expand/double-up the outer layer of pixels for each tile so interpolation doesn't sample a transparent pixel
- Flintlock I think is planning to just enlarge the texture a tiny % to do the same thing as the previous option.

(I think the second option is the most correct and least hackish. Since the base tile map rarely if ever changes, that also makes a lot of logical sense.)

**Comment by QuintillusCFC** [comment]
Yeah, that's an interesting idea to make a whole map texture.  I think the only time it would change is if global warming affects a tile that doesn't have forest/marsh/jungle.  I'm inclined to agree that it's probably the least hackish.  So long as the texture isn't way too big, it might even improve performance by saving us some draw calls.

**Comment by QuintillusCFC** [comment]
Moving to Carthage since it's going to be too big of a change to fit in Babylon without delaying it even further.

**Comment by Kright** [comment]
I think there is another option available: custom shader. 
```
if (color.a > 0.0){
    color.rgba /= color.a;
}
```
For example, if four texels are interpolated and two of them transparent, color.a == 0.5. So result is opaque if at least one of intepolated pixel is opaque and color is averaged between opaque pixels
