### ISSUE TITLE
Add a proper logging framework

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#118]
We have an increasing number of Console.WriteLine and GD.Print statements.  There are two downsides to this:

1. There's no granularity control.  No option to say, "print more stuff in debug mode".
2. There's no ability to send it all to a log file.  Having that ability will likely be useful for bug reports.

This is to figure out which framework to use and to start using it.  Known candidates include Log4Net, NLog, and Serilog.

**Comment by WildWeazel** [comment]
I know @TinaFemea had some opinions on this

**Comment by TinaFemea** [comment]
I do!!  

There are generally two ways to fail at logs.  You can not log enough, and then they are useless, or you can log too much, and then you can't find what you want, and then they are useless.  

Log levels are great, and should be used consistently, in whatever levels the library you support has.  I like Fatal/Error/Warning/Info/Debug.

At the debug level, everything should have a tag.  In your case, you would have things like "troop_movement" or "player_action" or "state_changed".  A giant enum with all the options is easiest.  Then, when you do turn on debug log level, you give it a set of tags (or "all") and it logs just those tags.  Because generally when you're turning on debug logs you're looking at or for a problem in one specific area.

We wrote our logging subsystem by hand before Log4Net was widely used, but if I had to start over again I'd definitly just pick up Log4Net.

Another interesting logging idea:   Generally, logging in debug mode all the time isn't feasible - the file IO can kill performance, and even with generous log file sizes, it's not uncommon for the thing you're looking for to roll off the end.  As a alternative, you can have instant-replay-logging for particularly critical subsystems.  Turn on debug logging for those tags to a memory stream all the time, then if any one of a set of events happen, immediately write out that stream to a file (which is then subject to the usual disk space/rollover limits).   This gives you really great crash logs!!
