### ISSUE TITLE
Project solution fails to build after Visual Studio-related changes

### ISSUE THREAD

**Issue by maxpetul** [C7-Game/Prototype#162]
The game is now failing to build for me after that "VSStub" project was added to C7.sln. Here's the error message, copied from my Linux system though I also tried on Windows and got the same error:
```
       "/media/r/proj/C7/Prototype/C7/C7.sln" (Build target) (1:2) ->
       "/media/r/proj/C7/Prototype/C7/VSStub/VSStub.csproj" (default target) (7:6) ->
       (GetReferenceAssemblyPaths target) -> 
         /usr/share/dotnet/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/media/r/proj/C7/Prototype/C7/VSStub/VSStub.csproj]
```
It suggests installing the 4.7.2 targeting pack, except I already have that installed. On Windows I tried rerunning the installer to "repair" my installation but that didn't fix the problem. I don't know what else to try. In the mean time I can work around the issue by deleting the "Project ... EndProject" lines for "VSStub" from C7.sln. After that the game builds and appears to work normally, which makes me wonder if this "VSStub" project is needed at all.

**Comment by QuintillusCFC** [comment]
Unfortunately, that's the only way to get debugging working with Visual Studio currently.  It's supposed to be easier, but there was a change in the C# project format, and they have a bug thread at https://github.com/godotengine/godot-csharp-visualstudio/issues/10 where the VSStub is the work-around to the bug.

Puppeteer mentioned the format change at https://forums.civfanatics.com/threads/dev-visual-studio-2019-impressions.675739/#post-16237872

WildWeazel mentioned a similar issue when we were prepping the Babylon release, although at that point we thought it was only an issue on Linux.  It seems it isn't :(.  So the question is, why does it work on my machine, even if I launch it from Godot directly?  I'm guessing you are trying to launch it from the Godot editor directly?

Possibly relevant details: I have the .NET desktop development, Desktop development with C++, and Mobile Development with .NET packs installed for Visual Studio 2019 (the latter is required by the Godot extension for Visual Studio).  I also have the Visual Studio Build Tools 2019, including the C++ build tools.

If the correct way to check targeting pack installations is at https://stackoverflow.com/questions/50006363/how-to-check-programmatically-if-net-4-7-target-pack-is-installed, then I have 3.5, 4.0, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.7.2, 4.8, and 4.X installed, but that's way more than I expected, and in theory 4.7.2 should work.  I'm not really sure how to check that on the command line though, being primarily a Java developer.

We might have to drop Visual Studio support again, if we can't find a work-around.  @WildWeazel and @JimOfLeisure probably know more about C#/.NET than I do, judging by past conversations.  Maybe they'll have an idea of why it works on some machines but not others.

**Comment by JimOfLeisure** [comment]
@QuintillusCFC What do each of you have in Godot under Editor -> Editor Settings -> Mono / Builds? If I have "MSBuild (Mono)" selected it still works. If I have "dotnet CLI" selected it fails on build with:

> /usr/local/share/dotnet/sdk/6.0.101/Microsoft.Common.CurrentVersion.targets(1217,5): The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

(This is on an Intel Mac, by the way)

**Comment by QuintillusCFC** [comment]
Well, unfortunately for predictability, I have "dotnet CLI" (in Godot 3.4.3 x86, Windows 8.1), and it's working...

**Comment by QuintillusCFC** [comment]
If I use MSBuild (Mono), it fails:

```C:\Development\Civ Related Projects\Prototype\C7\C7.csproj(0,0): The SDK resolver type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.MSBuildSdkResolver.VSSettings' threw an exception.```

MSBuild (VS Build Tools) works.  MSBuild (JetBrains Rider) fails, simply saying, "The build method threw an exception.".  All of these are building from within Godot.  I'm guessing the JetBrains one failed because my trial expired.

**Comment by JimOfLeisure** [comment]
Yeah, I just fired it up on Windows...and dotnet works but Mono fails on C7Engine! But I don't even know if I ever had Mono working on that box, and the error is about resolving MSBuild or something, so pay no attention to my Mono Windows failure to build.

I *do* have Visual Studio installed on that box. (I hate myself for having done so...not a VS fan.)

Ok your ~~edit~~ new post just popped in while I was typing this...yeah that's the Mono error I got on Win.

...but it *does* say VSSettings....hmmm

**Comment by QuintillusCFC** [comment]
Here's the output of `dotnet --list-sdks` for me:

```
2.2.300 [C:\Program Files\dotnet\sdk]
5.0.404 [C:\Program Files\dotnet\sdk]
5.0.405 [C:\Program Files\dotnet\sdk]
6.0.201 [C:\Program Files\dotnet\sdk]
```

That might be relevant...

**Comment by WildWeazel** [comment]
On x86_64 Linux, switching to MSBuild resolves one of the 3 build errors:

dotnetCLI:
`/usr/share/dotnet/sdk/5.0.406/Microsoft.Common.CurrentVersion.targets(1217,5): The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks`
`/usr/share/dotnet/sdk/5.0.406/Roslyn/Microsoft.CSharp.Core.targets(71,5): ERROR: ld.so: object '/home/travis/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`/usr/share/dotnet/sdk/5.0.406/Roslyn/Microsoft.CSharp.Core.targets(71,5): ERROR: ld.so: object '/home/travis/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

MSBuild:
`/usr/lib/mono/msbuild/Current/bin/Roslyn/Microsoft.CSharp.Core.targets(59,5): ERROR: ld.so: object '/home/travis/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`/usr/lib/mono/msbuild/Current/bin/Roslyn/Microsoft.CSharp.Core.targets(59,5): ERROR: ld.so: object '/home/travis/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

SDKs:
`> dotnet --list-sdks`
`5.0.406 [/usr/share/dotnet/sdk]`

**Comment by QuintillusCFC** [comment]
On my laptop (Windows 10, Godot 3.4 x64):

dotnet --list-sdks yields `2.2.300 [C:\Program Files\dotnet\sdk]`

dotnet CLI works.  Interesting that it works with that old version.

MSBuild (mono) yields `The build method threw an exception.`, and the hovertext says it couldn't find the executable for MSBuild (mono).  Same for MSBuild (Rider), basically the same for MSBuild (VS Build Tools).

So...

 - dotnet CLI + Windows are friends, for the data we have so far
 - Mono on Windows has only been seen working on my machine with VS Build Tools
 - On Mac, Mono + MSBuild is working, dotnet CLI isn't
 - On Linux, nothing is working
 - On the GitHub build system which I believe is also Linux, it does work.  Not sure if it's using dotnet CLI or Mono there.

Meanwhile, @Sean-Brown picked up the project and doesn't seem to have run into an issue with this.

I think there must be something going on with Mono/.NET installs that we haven't properly documented, it seems very inconsistent so far.  I'm also kind of confused about the ELF errors that @WildWeazel is seeing... are those really new with the VSStub project?  It looks like it's complaining that an executable file isn't in the correct format for the operating system.

We have had similar discussions in the Godot/Mono Synchronization thread, and here: https://forums.civfanatics.com/threads/dev-0-1-babylon-progress-thread.673959/page-7#post-16201077 

I think the plan should be:
 - Document our findings/supported configurations.  We have been in the Wild West as to which build system we use, which is probably not ideal.  But I don't know which one we should use.
 - It would be good to determine the _why_ of why some of the configurations aren't working.  But this will probably have to be done by someone whose configuration isn't working; since all of them work for me if I have them installed on the machine in test, I can't be the person who figured out why it isn't working/what's missing from the install.
 - We should try to understand what's going on a little better before throwing out Visual Studio again, especially since Flintlock has found a work-around.  The Mono/dotnet CLI stuff has caused some problems before, and my hunch is that they are related to the Visual Studio problem.

**Comment by WildWeazel** [comment]
> I'm also kind of confused about the ELF errors that @WildWeazel is seeing... are those really new with the VSStub project? It looks like it's complaining that an executable file isn't in the correct format for the operating system.

They are new since the debugging project, and that is what they mean, but I hadn't looked closely beyond that first one. The problematic library is the overlay that appears when you launch a program from Steam. If I start the Godot executable directly those go away. So, dotnetCLI does not work but MSBuild does as long as I don't launch from Steam. (I haven't tried actually debugging yet, but I can at least build & run again.)

**Comment by QuintillusCFC** [comment]
Oh, interesting.  I knew it was possible to download Godot from Steam, but had just been downloading it from the website myself.  But I hadn't guessed that the Steam overlay library could have an impact on whether the project would launch :crazyeye:.

**Comment by JimOfLeisure** [comment]
> On the GitHub build system which I believe is also Linux, it does work. Not sure if it's using dotnet CLI or Mono there.

It's Mono. Is uses the mono:latest Docker image to build, or rather it uses barichello/godot-ci:mono-3.4 , and *that* uses mono:latest.

@WildWeazel 's 2 consistent errors have `.steam` in them and file structures that look nothing like C7. He's got something else going on.

Edit: Looks like WW is trying to load 32-bit libraries in the .steam folder. That should have nothing to do with our project. Did this same setup work before the VSStub addition? Try checking out an older commit and try it?

Edit 2: I may have cross-posted. So the cli is invoking the Steam overlay?

**Comment by JimOfLeisure** [comment]
A thought, and I'm not sure what to make of this:

- WW knows there is an issue with the Steam overlay, and the VS debug code is somehow triggering (?) this overlay on build
- Flintlock has had intermittent issues with the Civ3 path being found on alternate Godot invocations

Maybe something about the VS debug stub opens a context that triggers the overlay on WW's Linux box and ... no, Flintlock's registry issue would be runtime, not build-time.

Well, it was a thought...I don't see it going anywhere.

**Comment by WildWeazel** [comment]
Just to be clear: of the 3 build errors I listed above, the first only happens with dontnetCLI and the rest only happen if I launch via Steam, but all of them were only introduced with the VS debugging changes and go away if I revert that commit. After some more fiddling with the snippets posted in the support thread I was able to get the debugger working.

**Comment by QuintillusCFC** [comment]
Since we removed the Visual Studio related changes in May, I'm going to close this as obsolete.  Feel free to re-open or spin something off for the Steam overlay issue.
