### ISSUE TITLE
Flashing and illegible city UI

### ISSUE THREAD

**Issue by WildWeazel** [C7-Game/Prototype#171]
At certain zoom levels, and especially after zooming, the city info boxes flash white. It's probably best to hide them past a certain zoom level anyway, or devise a scheme to hide or simplify different things like the strategic view in Civ5, because they become illegible smears.

See also #172

**Comment by QuintillusCFC** [comment]
I've also noticed this happen late game (200+ turns into the game), even at 100% zoom.  It could be related to the number of things being displayed, which is artificially high late game with ICS and units all over the place, but I also suspect my implementation of the city UI is highly sub-optimal, as it was back in Aztec days when I was still pretty new to Godot.  Thanks for writing it up!

**Comment by QuintillusCFC** [comment]
I took a stab at figuring this out tonight; see the 171-Debugging-Attempt branch.

Long story short, I didn't succeed.  I removed progressively more code, but this line:

```
looseView.DrawTextureRectRegion(label, labelDestination, allOfTheLabel);
```

Stubbornly causes the flashing white rectangle even as the label becomes as simple as a red rectangle, and removing everything else doesn't help.  Unfortunately, that line is kind of important as `label` contains almost all the graphics for the city label.  The only thing it doesn't contain is the text (and the city graphics themselves).

Logic would seem to dictate that a small percentage of the time, the `labelImage` from which `label` is created doesn't get any graphics drawn to it for some reason, and is thus just a white rectangle.  But why?  When?  Is one of the methods we are calling asynchronous, and not returning in time occasionally?  Nothing is jumping out as the cause...

**Comment by QuintillusCFC** [comment]
The flashes seem to be correlated with these Godot errors that have long bamboozled us:

```
ERROR: Condition "!id_map.has(p_rid.get_data())" is true. Returned: nullptr
```

Indeed, removing the line mentioned above seems to remove them.  But why?

**Comment by WildWeazel** [comment]
Interesting that they are connected. I wonder if creating even a very simple scene instead of drawing it programmatically would have any effect.

**Comment by QuintillusCFC** [comment]
Tried out Godot 3.4.5 RC1, the problem persists there.  So if it's an engine thing, it isn't fixed yet.  Seems to be a common error that people run into and don't know how to fix...

**Comment by QuintillusCFC** [comment]
> Interesting that they are connected. I wonder if creating even a very simple scene instead of drawing it programmatically would have any effect.

Maybe.  I know we have a refactor for that, too.  I just kind of dove into this after adding some tile visibility as it seemed to be happening more tonight for some reason (maybe because Civ3 is up in the background?  who knows).

With the new knowledge that it is related to Image or ImageTexture in some way, I was able to refine my search terms, and found https://github.com/godotengine/godot/issues/24834, which suggests that the ImageTexture might be getting garbage collected, essentially.  And, hmm, I suppose that is a difference relative to our other code, where we store the loaded-from-PCX ImageTexture in a scope that persists for the life of the layer drawing with it.

And that seems to be it!  I'll probably jinx myself by writing this, but by moving the ImageTexture to the front of CityLayer.cs, it seems to have solved the problem.
