### ISSUE TITLE
Create a City UI scene

### ISSUE THREAD

**Issue by WildWeazel** [C7-Game/Prototype#172]
Create a single reusable and scriptable Godot scene to display a more faithful city UI: the shaded, color-coded box containing the size, name, growth time, production project and time, capital icon, and barracks/harbor/airport icons (some discussion may be needed about how to generalize those), with a container for the city graphic and overlay animation. The scene should have functions to update/set each of these elements either programmatically or via editor controls.

This may obviate #171

**Comment by QuintillusCFC** [comment]
Thought about this a bit tonight when making it so not all cities display as capitals.  The thing that's tough to wrap my mind around is how a Godot Scene of a city and our LooseLayer concept are supposed to intertwine.

Currently, the map is run via MapView.cs, with a LooseLayer for each layer, one of which is CityLayer.cs.

MapView handles all the logic around drawing things in the right place, panning the map, etc.

Looking at C7Game.tscn, all the nodes within that scene are anchored and margined in various ways to that scene.  Which works fine for UI interactions, but doesn't extend nicely to cities on a pannable map as far as I can tell.

Actually, looking more into the code, it looks like a Scene _is a _ Node2D, as Game.cs (the C# class that goes along with C7Game.tscn) is a Node2D.  LooseLayer is also a Node2D.  So by that logic, LooseLayer _is a _ Scene.  It's just a scene that we extend in various ways.

That means that technically, CityLayer _is a_ Node2D, and thus CityLayer is a UI scene.  It just renders all the cities rather than one.

Thus with a progammer's lens, what this amounts to is making a Node2D that encapsulates all the per-city graphics.  We don't need a .tscn and its anchors/offsets of components, because it's only going to be used within the LooseLayer concept.

Let me know if that makes sense.  It didn't when I started writing it but I think it does now.

**Comment by QuintillusCFC** [comment]
See the commits on the branch mentioned above; I have started down this route but am running into some issues with drawing strings.  Going to revisit it later with a fresh mindset unless someone else wants to pick it up first.  That may be a good idea as I know WildWeazel has more game engine experience than I do.

**Comment by QuintillusCFC** [comment]
I have figured out some things and I think this is now working relatively well.  It isn't entirely "modernized" as WildWeazel describes, but it is functional, and I've started to be able to make optimizations that the old way of doing things didn't allow, namely only re-drawing the label background if the data has changed.

The label itself could probably also be broken out as a scene; much of the logic in the new scene (and the old code) concerns how to draw the label, so that would also be beneficial.
